"""
check_adl_no_asserts.py
Checks that an ADL file contains NO assert statements.

The Wright# verifier (verify_wrighthash_all_properties.py) reads assertions
from tmp/assertions.md and applies path-filtering per partial system. Any
`assert` lines embedded in the ADL file are preserved verbatim in every
partial system generated by update_adl_with_new_attachments(), bypassing
the per-system filter. This causes PAT to error on assertions referencing
components absent from the current partial system.

Rule: tmp/refactored.adl must NOT contain any assert statements.
All assertions belong exclusively in tmp/assertions.md.

Usage:
  python3 check_adl_no_asserts.py <adl_file_path>
Exit 0: no assert statements found — ADL file is clean.
Exit 1: one or more assert statements detected — must be removed.
"""

import sys
import re


def find_assert_statements(adl_text):
    """
    Returns a list of (line_number, line_content) for every line
    that contains an assert statement (excluding comment-only lines).
    Matches lines where 'assert' appears as a statement keyword,
    not inside a comment.
    """
    violations = []
    for lineno, line in enumerate(adl_text.splitlines(), start=1):
        stripped = line.strip()
        # Skip pure comment lines
        if stripped.startswith('--'):
            continue
        # Match assert keyword at start of statement (after optional whitespace)
        if re.search(r'\bassert\b', stripped):
            violations.append((lineno, line.rstrip()))
    return violations


def main():
    if len(sys.argv) < 2 or sys.argv[1] == '--test':
        if len(sys.argv) >= 2 and sys.argv[1] == '--test':
            success = run_tests()
            sys.exit(0 if success else 1)
        print("Usage: python3 check_adl_no_asserts.py <adl_file_path>")
        sys.exit(1)

    adl_path = sys.argv[1]
    try:
        with open(adl_path, 'r') as f:
            adl_text = f.read()
    except FileNotFoundError:
        print(f"ERROR: File not found: {adl_path}")
        sys.exit(1)

    violations = find_assert_statements(adl_text)

    if violations:
        print(f"ERROR: {len(violations)} assert statement(s) found in ADL file.")
        print("Assert statements must be placed ONLY in tmp/assertions.md, NOT in the ADL file.")
        print("The verifier embeds all ADL text verbatim into every partial system, causing PAT errors.")
        print()
        for lineno, line in violations:
            print(f"  Line {lineno}: {line}")
        sys.exit(1)
    else:
        print("No assert statements found in ADL file. ADL file is clean.")
        sys.exit(0)


# ---------------------------------------------------------------------------
# Test suite (run with: python3 check_adl_no_asserts.py --test)
# ---------------------------------------------------------------------------

TEST_CASES = [
    (
        "Clean ADL — no assert statements",
        """
connector CSConnector {
  role requester(j) = process -> req!j -> res?j -> Skip;
  role responder() = req?j -> invoke -> process -> res!j -> responder();
}

component Alpha {
  port send() = sent -> send();
}

system mysys {
  declare wire = CSConnector;
  attach Alpha.send() = wire.requester(1);
  execute Alpha.send();
}
""",
        []  # no violations expected
    ),
    (
        "ADL with assert statement at end",
        """
system mysys {
  declare wire = CSConnector;
  attach Alpha.send() = wire.requester(1);
  execute Alpha.send();
}

assert mysys |= [] (Alpha.send.sent -> <> Beta.recv.received);
""",
        [("assert mysys |= [] (Alpha.send.sent -> <> Beta.recv.received);", 8)]
    ),
    (
        "ADL with multiple assert statements",
        """
system mysys {
  execute Alpha.send();
}

assert mysys |= [] (Alpha.send.sent -> <> Beta.recv.received);
assert mysys |= [] (Beta.recv.received -> <> Gamma.proc.processed);
""",
        [
            ("assert mysys |= [] (Alpha.send.sent -> <> Beta.recv.received);", 6),
            ("assert mysys |= [] (Beta.recv.received -> <> Gamma.proc.processed);", 7),
        ]
    ),
    (
        "Assert in comment only — should NOT be flagged",
        """
-- assert: this is just a comment about assertions
system mysys {
  execute Alpha.send();
}
""",
        []  # comment lines are excluded
    ),
    (
        "Inline assert after code — should be flagged",
        """
system mysys {
  execute Alpha.send();
}
assert mysys |= [] (<> Alpha.send.sent);
""",
        [("assert mysys |= [] (<> Alpha.send.sent);", 5)]
    ),
]


def run_tests():
    passed = 0
    failed = 0

    for desc, adl_text, expected_violations in TEST_CASES:
        violations = find_assert_statements(adl_text)

        ok = True
        if not expected_violations:
            if violations:
                print(f"FAIL [{desc}]: expected no violations, got {len(violations)} violation(s): {violations}")
                ok = False
        else:
            # Check that the expected number of violations were found
            if len(violations) != len(expected_violations):
                print(f"FAIL [{desc}]: expected {len(expected_violations)} violation(s), got {len(violations)}: {violations}")
                ok = False
            else:
                for (exp_content, exp_lineno), (got_lineno, got_content) in zip(expected_violations, violations):
                    if exp_content.strip() not in got_content:
                        print(f"FAIL [{desc}]: expected content '{exp_content}' not found in '{got_content}'")
                        ok = False
                    if got_lineno != exp_lineno:
                        print(f"FAIL [{desc}]: expected line {exp_lineno}, got line {got_lineno}")
                        ok = False

        if ok:
            print(f"PASS [{desc}]")
            passed += 1
        else:
            failed += 1

    print(f"\n{passed} passed, {failed} failed.")
    return failed == 0


if __name__ == '__main__':
    if len(sys.argv) == 2 and sys.argv[1] == '--test':
        success = run_tests()
        sys.exit(0 if success else 1)
    main()
